config/routes.rb
Book::Application.routes.draw do
    get "welcome/index"
    resources:posts
    devise_for :users, :path => "auth", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }
    root 'posts#index'
    delete "devise/sessions#destroy"

  

end

app/models/post.rb
class Post < ActiveRecord::Base
    self.per_page = 4
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
        if user_signed_in?
            @post = Post.new
        else
            redirect_to user_session_path
        end
    end
    
    def create
        @post = Post.new(params[:post].permit(:title, :text))
        @post.title = current_user.email
        @post.save
        redirect_to @post
    end
    
    def show
        @post = Post.find(params[:id])
    end
    
    def index
        @post = @posts = Post.paginate(:page => params[:page])
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def update
        @post = Post.find(params[:id])
        
        if @post.update(params[:post].permit(:title, :text))
            redirect_to @post
        else
            render 'edit'
        end
    end
    
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        
        redirect_to posts_path
    end
    
    private
        def post_params
            params.require(:post).permit(:title, :text)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
    def xyz
        puts 'dinar'
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Book</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1 align="center">Edit message</h1>

<%= form_for :post, url: post_path(@post.id), method: :patch do |f| %>
    <% if @post.errors.any? %>
    <div id="errorExplanation">
        <h2><%= pluralize(@poat.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    </div>
    <% end %>
    <p align="center">
        
        <%= f.text_area:text %>
    </p>
    
    <p align="center">
        <%= f.submit 'Send' %>
    </p>
<% end %>
<p  align="center">
    <%= link_to 'Back', posts_path %>
</p>

app/views/posts/index.html.erb
<h1 align="center">GuestBook</h1><br>

<% if user_signed_in? %>
    <h3><%= link_to 'Send a message', new_post_path %></h3>
    <h3><%= link_to 'Exit', destroy_user_session_path , session[:user] = nil %></h3>
<% else %>
    <h3><%= link_to 'Registration' , new_user_registration_path %>
    <h3><%= link_to 'Authorization' , user_session_path %></h3>
    <h3><%= link_to 'Send a message', new_post_path %></h3>
<% end %>

<% @post.each do |post| %>
    <table style="background-color: grey ; word-wrap: break-word;" align="center">
        <tr><td><h3><%= post.title %></h3></td></tr>
        <tr><td><%= post.text %></td></tr>
        <% user_signed_in? && if post.title == current_user.email %>
            <tr><td><%= link_to 'Edit', edit_post_path(post) %></td><td><%= link_to 'Destroy', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td></tr>
        <% end %>
    </table>
    <br><br>
<% end %>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h2 align="center">New message</h2>

<%= form_for :post, url: posts_path do |f| %>
 
  <p align="center">
    <%= f.text_area :text %>
  </p>
 
  <p align="center">
    <%= f.submit 'Send' %>
  </p>
<% end %>
<p align="center">
    <%= link_to 'Back', posts_path %>
</p>

app/views/posts/show.html.erb
<p>
  <h3>User:</h3>
  <%= @post.title %>
</p>
 
<p>
  <h3>Message:</h3>
  <%= @post.text %>
</p>
<p>
<%= link_to 'Back', posts_path %>
<%= link_to 'Destroy', edit_post_path(@post) %>
</p>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<h1 align="center">Главная</h1>

<h3 align="center"><%= link_to 'Авторизация' , user_session_path %></h3>
<h3 align="center"><%= link_to 'Гостевая книга' , posts_path %></h3>